# NOTE: update this with your service name
service: numisapp

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: numisapp-theo-assets
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  create:
    handler: functions/create.main
    events:
      - http:
          path: products
          method: post
          cors: true
          authorizer: aws_iam

  get:
    handler: functions/get.main
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list:
    handler: functions/list.main
    events:
      - http:
          path: products
          method: get
          cors: true
          authorizer: aws_iam

  update:
    handler: functions/update.main
    events:
      - http:
          path: products/{id}
          method: put
          cors: true
          authorizer: aws_iam

  delete:
    handler: functions/delete.main
    events:
      - http:
          path: products/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  billing:
    handler: functions/billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
